---
apiVersion: kustomize.toolkit.fluxcd.io/v1alpha1
kind: Kustomization
metadata:
  creationTimestamp: null
  name: webapp-common
  namespace: gitops-system
spec:
  interval: 1h0m0s
  path: ./deploy/webapp/common
  prune: true
  sourceRef:
    kind: GitRepository
    name: webapp
  validation: client
status: {}

